### ISSUE TITLE
[BUG] Internal Exception: io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by TheTrippyTree** [LoneDev6/ItemsAdder#372]
**Describe the bug**
After adding some custom recipes to my server, I'm unable to join it.

When I try to join, this is as far as I get:

![image](https://user-images.githubusercontent.com/43531808/91918349-a7083480-ec90-11ea-822f-ed651cb5fc40.png)

There are 513 custom recipes on this server and I'd like to add more. When I disable a bunch of the recipes, it works again after restarting the server. Is this a Minecraft limitation, or is it something that could be fixed?

The issue still occurs with all of the other plugins removed.

I don't believe this is a configuration issue as it appears to depend solely on the number of recipes. The problematic number of custom recipes appears to be 500.

499 custom recipes works as intended.

Enabling the recipes and reloading ItemsAdder while already on the server allows you to use the recipes, but as soon as you leave you are unable to join again.

**To Reproduce**
1. Add 500+ custom recipes
2. Run server
3. Join server

**Info (please complete the following information):**
 - Server version: Spigot 1.16.2
 - Client version: Minecraft 1.16.2 with and without Optifine 1.16.2 G3
 - Plugin version: 2.0.43

**Comment by LoneDev6** [comment]
Seems to be a Minecraft bug I think, seems the recipes book supports only 500 recipes: https://bugs.mojang.com/browse/MC-185901

Damn.. I think I can't do much about it, I'd have to stop sending the recipes packet completely on join, do you think it's a solution?

**Comment by TheTrippyTree** [comment]
Yeah. That’s what I figured unfortunately. Seems like Mojang is in no hurry to fix it either.

I did some additional testing with enabling the recipes while on already on the server. It turns out that only the first 500 recipes actually work. So while disabling the initial packets would allow players to join, this would only solve half of the problem. Or at least so I think. Might still be worth a shot?

The only other solution I could see working would be creating a custom crafting table that could potentially replace the default one. This way the plugin would be responsible for crafting. Could this work? I wonder if there’s some plugin that already does this. Might make the recipe book useless, but who ever used it anyway?

**Comment by LoneDev6** [comment]
I think I found the issue and I can fix it. I already stop the server from sending custom recipes to the recipebook to 
fix a duplication bug (which occured only with recipes that has renamed items in the ingredients) but I failed to stop another part of the packet which still contains data. Cleaning also this part of the packet should fix the issue.

I think that recipes book is quite useless at its stage, yes, but Mojang has definitely to fix this.


Please download the new update and let me know (I will publish it later)

**Comment by TheTrippyTree** [comment]
The fix was included in the 2.0.44 update, right?

I downloaded it and unfortunately I still cannot join after going from 499 recipes to 500.

**Comment by LoneDev6** [comment]
I think the only solution is to remove the player .dat file using this tool: https://irath96.github.io/webNBT/

![image](https://user-images.githubusercontent.com/27242001/92275272-1ed39a80-eeef-11ea-953b-919d187ac500.png)
Right click recipes and delete, then save and start the server


You have to do this to each player. Or just delete the .dat files.. but they would lose last location, inventory...

**Comment by TheTrippyTree** [comment]
I tried the tool and also deleting the world & player data but to no avail.

Sadly, this might truly be Mojang's problem to fix. :(

**Comment by LoneDev6** [comment]
I will publish an update this week which should fix the issue once for all
