### ISSUE TITLE
[BUG] Issue with Crafting Table Output being Empty when crafting

### ISSUE THREAD

**Issue by SirCraftypants** [LoneDev6/ItemsAdder#530]
**Describe the bug**

No item in Output after Crafting it in a Crafting Table

**To Reproduce**
Craft something

**Expected behavior**
No item in output slot.

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: (example: Minecraft 1.15.2)
 - Plugin version:  2.1.20

I have made sure i had the permission to craft the item and attempted to craft the item but nothing appeared in the output.

All code is correct as it should be, must be a Plugin issue. 

I attempted this after a plugin user on discord reported the same problem, it's happening for me also.

The Recipe i attempted to craft was comprised of only custom items creating a custom item, all namespaced correctly in the recipe.

**Comment by diontimmer** [comment]
+1 on this, discussed this with crafty on discord. seems to happen more when there are no vanilla items present in the recipe; only IA items. It does not throw anything in the console although denizen picks up that theres something with the "itemsadder" nbt in the blank crafting output.

**Comment by LoneDev6** [comment]
That's very stange.
Can I get more details on which recipes have this problem? I've never changed the recipes code in months, so the fact that this issue started happening randomly is very strange.

**Comment by SirCraftypants** [comment]
This is the example i used to test  with https://paste.helpch.at/gojekarari.css

**Comment by LoneDev6** [comment]
Try to add a permission, seems a malformed recipe to me.
This is fixed:
```yml
    wedges_pot:
      permission: wedges_pot
      enabled: true
      pattern:
      - XXX
      - XWX
      - XPX
      ingredients:
        W: customitems:wedges
        P: customitems:empty_wedges_pot
      result:
        item: customitems:wedges_pot
        amount: 1 
```

let me know

**Comment by SirCraftypants** [comment]
OK I made a mistake, i was using the wrong pot item, mines working fine, I will continue support with Dion Timmer and see if i can solve his issue. if not then i'll get him to continue here with his issue.

**Comment by diontimmer** [comment]
Will have a look today if theres something wrong with the recipe setup, it does show up in the GUI but there might be something like a perm off like you noticed. Will let you know incase you want to squeeze a warning in there

**Comment by diontimmer** [comment]
i tried adding a permission but it still does not seem to craft properly anymore, which is strange since my players have crafted these items in the past

```    cdjs:
      enabled: true
      permission: vextracraft.user
      pattern:
      - WGW
      ingredients:
        W: vextracraft:cdj
        G: JUKEBOX
      result:
        item: vextracraft:cdjs
        amount: 1```

this is the config for the current item, changing "vextracraft:cdj" to OAK_WOOD seems to make it craftable. I am certain the namespace and naming is correct since the item shows up correctly in the gui

**Comment by spiker5032** [comment]
It seems that these mess up when using a furniture model in your recipe.

So Menorah1 and Menorah are Furnitures. You can place them and they give off light.
But when using this to (Light) The second one I do not get anything.
It seems like using Furnitures/Models causes this bug.

`    menorah1:
      permission: jinglejammin.menorah1
      enabled: true
      pattern:
      - XXX
      - XPX
      - XXX
      ingredients:
        P: jinglejammin:menorah
      result:
        item: jinglejammin:menorah1
        amount: 1
      return_items:
        decrement_durability:
          FLINT_AND_STEEL:
            item: FLINT_AND_STEEL
            amount: 1`

**Comment by LoneDev6** [comment]
> 
> 
> i tried adding a permission but it still does not seem to craft properly anymore, which is strange since my players have crafted these items in the past
> 
> ```
>       enabled: true
>       permission: vextracraft.user
>       pattern:
>       - WGW
>       ingredients:
>         W: vextracraft:cdj
>         G: JUKEBOX
>       result:
>         item: vextracraft:cdjs
>         amount: 1
> ```
> 
> this is the config for the current item, changing "vextracraft:cdj" to OAK_WOOD seems to make it craftable. I am certain the namespace and naming is correct since the item shows up correctly in the gui

Pattern must contain 3 lines if I recall correctly, so:
```
      enabled: true
      permission: vextracraft.user
      pattern:
      - XXX
      - XXX
      - WGW
      ingredients:
        W: vextracraft:cdj
        G: JUKEBOX
      result:
        item: vextracraft:cdjs
        amount: 1
```

Anyway guys, each user of this github issue has a different problem and this report got messy.
Please if any of you still have issues with recipes open a different github ticket for each of the problems explaining what happens, thanks all for the patience.


@SirCraftypants  let me know if the original issue is still valid or if I can close this report, thanks!
